## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [2]:
model1 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 4)),
    ('activation1', nn.ReLU()),
    ('hidden2', nn.Linear(4, 2)),
    ('activation2', nn.ReLU()),
    ('output', nn.Linear(2, 2)),
    ('sigmoid', nn.Sigmoid()) 
]))

model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 3)),
    ('activation', nn.ReLU()),
    ('output', nn.Linear(3, 2)),
    ('sigmoid', nn.Sigmoid())
]))

model3 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 8)),
    ('activation1', nn.ReLU()),
    ('hidden2', nn.Linear(8, 8)),
    ('activation2', nn.ReLU()),
    ('output', nn.Linear(8, 2)),
    ('sigmoid', nn.Sigmoid())
]))

model=model1
epoch=2000
learning_rate=0.01

In [3]:
print(model)

Sequential(
  (hidden1): Linear(in_features=2, out_features=4, bias=True)
  (activation1): ReLU()
  (hidden2): Linear(in_features=4, out_features=2, bias=True)
  (activation2): ReLU()
  (output): Linear(in_features=2, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)


In [4]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([[0,0],[0,1],[1,0],[1,1]])
print(data_in)

tensor([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]])


In [5]:
# your code here
data_target = torch.tensor([[0,0],[1,0],[1,0],[0,0]])

print(data_target)

tensor([[0, 0],
        [1, 0],
        [1, 0],
        [0, 0]])


In [6]:
# your code here
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


In [7]:
# your code here
# Train the model

# Convert tensors to float type 
data_in_float = data_in.float()
data_target_float = data_target.float()

for epoch in range(epoch):
    optimizer.zero_grad()  
    output = model(data_in_float)  
    loss = criterion(output, data_target_float)  
    loss.backward()  
    optimizer.step() 

    if epoch % 100 == 0:
        print(f'Epoch {epoch}, Loss: {loss.item()}')
# Test the model
with torch.no_grad():
    test_input = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
    test_output = model(test_input)
    
    # Show rounded predictions for clearer understanding of binary outputs
    print("\nRounded test output:")
    rounded_output = torch.round(test_output)
    print(rounded_output)
    
    # Compare with target data to evaluate accuracy
    print("\nExpected outputs:")
    print(data_target)

Epoch 0, Loss: 0.18462201952934265
Epoch 100, Loss: 0.1002073660492897
Epoch 200, Loss: 0.08365438133478165
Epoch 300, Loss: 0.08346957713365555
Epoch 400, Loss: 0.08341974020004272
Epoch 500, Loss: 0.08338891714811325
Epoch 600, Loss: 0.08341211825609207
Epoch 700, Loss: 0.08337251842021942
Epoch 800, Loss: 0.08336027711629868
Epoch 900, Loss: 0.08335459977388382
Epoch 1000, Loss: 0.08335059881210327
Epoch 1100, Loss: 0.08334766328334808
Epoch 1200, Loss: 0.08334542065858841
Epoch 1300, Loss: 0.08334366232156754
Epoch 1400, Loss: 0.08334226906299591
Epoch 1500, Loss: 0.08334112167358398
Epoch 1600, Loss: 0.08334019035100937
Epoch 1700, Loss: 0.0833394005894661
Epoch 1800, Loss: 0.08333873003721237
Epoch 1900, Loss: 0.08333815634250641

Rounded test output:
tensor([[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.]])

Expected outputs:
tensor([[0, 0],
        [1, 0],
        [1, 0],
        [0, 0]])


In [8]:
# Save the model
torch.save(model.state_dict(), 'model.pth')
# Load the model
loaded_model = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 8)),
    ('activation1', nn.ReLU()),
    ('hidden2', nn.Linear(8, 8)),
    ('activation2', nn.ReLU()),
    ('output', nn.Linear(8, 2)),
    ('sigmoid', nn.Sigmoid())
]))

In [9]:
# your code here
# Save the model
torch.save(model.state_dict(), 'model.pth')
# Load the model
model_loaded = model
model_loaded.load_state_dict(torch.load('model.pth'))
model_loaded.eval()


Sequential(
  (hidden1): Linear(in_features=2, out_features=4, bias=True)
  (activation1): ReLU()
  (hidden2): Linear(in_features=4, out_features=2, bias=True)
  (activation2): ReLU()
  (output): Linear(in_features=2, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)